# Generated by Django 2.2.5 on 2022-06-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltrd',
            name='lid',
            field=models.CharField(default='', max_length=200),
        ),
    ]
